server:
  port: 8000
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  data:
    redis:
#      host: localhost
      host: redis
      port: 6379
      password: 123456
  application:
    name: business
  cloud:
      client:
        config:
          default: # 全局默认配置
            connect-timeout: 5000   # 连接超时时间（毫秒）
            read-timeout: 60000     # 读取超时时间（毫秒）

sa-token:
  token-name: Authorization     # 请求头中 Token 的名称
  timeout: 86400                # Token 有效期，单位秒 (这里设为 24 小时)
  is-concurrent: true           # 是否允许同一账号并发登录
  token-style: uuid             # Token 风格 (uuid 格式)
  is-log: false