# ==========================================
# 1. Redis 缓存服务
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        # 👇 1. 更新为阿里云的完整镜像地址
        image: crpi-uc092ktu9mbv7t37.cn-shenzhen.personal.cr.aliyuncs.com/hq869863/hq:redis-8
        # 👇 2. 确保策略为 Always
        imagePullPolicy: Always 
        command: ["redis-server", "--requirepass", "123456"]
        ports:
        - containerPort: 6379