# AI 模块部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai
        image: crpi-uc092ktu9mbv7t37.cn-shenzhen.personal.cr.aliyuncs.com/hq869863/hq:ai-1.0.0
        ports:
        - containerPort: 8001
---
# Business 模块部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business
  template:
    metadata:
      labels:
        app: business
    spec:
      containers:
      - name: business
        image: crpi-uc092ktu9mbv7t37.cn-shenzhen.personal.cr.aliyuncs.com/hq869863/hq:business-1.0.0
        ports:
        - containerPort: 8000
---
# RAG 模块部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      restartPolicy: Never
      containers:
      - name: rag
        image: crpi-uc092ktu9mbv7t37.cn-shenzhen.personal.cr.aliyuncs.com/hq869863/hq:rag-1.0.0
        ports:
        - containerPort: 8009